# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.0.1
_src_path: https://github.com/napari/napari-plugin-template
display_name: AFMSlicer
email: n.shephard@sheffield.ac.uk
full_name: Neil Shephard
github_repository_url: https://github.com/ns-rse/napari-afmslicer
github_username_or_organization: ns-rse
include_reader_plugin: true
include_sample_data_plugin: true
include_widget_plugin: true
include_writer_plugin: true
install_dependabot: true
install_precommit: true
license: GNU GPL v3.0
module_name: napari_afmslicer
plugin_name: napari-afmslicer
short_description: A simple plugin to use AFMSlicer with napari
