repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=18384"]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
        types: [python, yaml, markdown]
        exclude: ^(tests/resources|tests/__snapshots__|\.napari-hub)/.*$
      - id: mixed-line-ending
        types: [python, yaml, markdown]
        exclude: ^(tests/resources|tests/__snapshots__|\.napari-hub)/.*$
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: no-commit-to-branch
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        types: [python, yaml, markdown]
        exclude: ^(tests/resources|tests/__snapshots__|\.napari-hub)/.*$
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.3.1
    hooks:
      - id: black
  - repo: https://github.com/tlambert03/napari-plugin-checks
    rev: v0.3.0
    hooks:
      - id: napari-plugin-checks
  - repo: https://github.com/codespell-project/codespell
    rev: "v2.4.2"
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli; python_version<'3.11'
  - repo: https://github.com/numpy/numpydoc
    rev: v1.10.0
    hooks:
      - id: numpydoc-validation
        # exclude: ""
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.22.1
    hooks:
      - id: markdownlint-cli2
        args: []
  # https://mypy.readthedocs.io/en/stable/
  # you may wish to add this as well!
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.9.0
  #   hooks:
  #     - id: mypy
  - repo: local
    hooks:
      - id: pylint
        args: ["--rcfile=.pylintrc.toml"]
        name: Pylint
        entry: python -m pylint
        language: system
        files: \.py$
ci:
  autofix_prs: true
  autofix_commit_msg: "[pre-commit.ci] Fixing issues with pre-commit"
  autoupdate_schedule: monthly
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit-autoupdate"
  skip: [pylint] # Optionally list ids of hooks to skip on CI
